export default {
  "the-skeld": [
    {
      name: "Align Engine Output",
      types: ["Long"],
      locations: ["Upper Engine", "Lower Engine"],
    },
    {
      name: "Calibrate Distributor",
      types: ["Short"],
      locations: ["Electrical"],
    },
    {
      name: "Chart Course",
      types: ["Short"],
      locations: ["Navigation"],
    },
    {
      name: "Clean O2 Filter",
      types: ["Short"],
      locations: ["O2"],
    },
    {
      name: "Clean Vent",
      types: ["Short"],
      locations: ["Any room with a vent"],
    },
    {
      name: "Clear Asteroids",
      types: ["Long", "Visual"],
      locations: ["Weapons"],
    },
    {
      name: "Divert Power",
      types: ["Short"],
      locations: [
        "Electrical",
        "Communications",
        "Lower Engine",
        "Navigation",
        "O2",
        "Security",
        "Shields",
        "Upper Engine",
        "Weapons",
      ],
    },
    {
      name: "Empty Chute",
      types: ["Long", "Visual"],
      locations: ["O2", "Storage"],
    },
    {
      name: "Empty Garbage",
      types: ["Long", "Visual"],
      locations: ["Cafeteria", "Storage"],
    },
    {
      name: "Fix Wiring",
      types: ["Common"],
      locations: [
        "Electrical",
        "Storage",
        "Admin",
        "Navigation",
        "Cafeteria",
        "Security",
      ],
    },
    {
      name: "Fuel Engines",
      types: ["Long"],
      locations: ["Storage", "Upper Engine", "Storage", "Lower Engine"],
    },
    {
      name: "Inspect Sample",
      types: ["Long"],
      locations: ["MedBay"],
    },
    {
      name: "Prime Shields",
      types: ["Short", "Visual"],
      locations: ["Shields"],
    },
    {
      name: "Stabilize Steering",
      types: ["Short"],
      locations: ["Navigation"],
    },
    {
      name: "Start Reactor",
      types: ["Long"],
      locations: ["Reactor"],
    },
    {
      name: "Submit Scan",
      types: ["Long", "Visual"],
      locations: ["MedBay"],
    },
    {
      name: "Swipe Card",
      types: ["Common"],
      locations: ["Admin"],
    },
    {
      name: "Unlock Manifolds",
      types: ["Short"],
      locations: ["Reactor"],
    },
    {
      name: "Upload Data",
      types: ["Short"],
      locations: [
        "Cafeteria",
        "Communications",
        "Electrical",
        "Navigation",
        "Weapons",
        "Admin",
      ],
    },
  ],
  "the-airship": [
    {
      name: "Calibrate Distributor",
      types: ["Short"],
      locations: ["Electrical"],
    },
    {
      name: "Clean Toilet",
      types: ["Short"],
      locations: ["Lounge"],
    },
    {
      name: "Clean Vent",
      types: ["Short"],
      locations: ["Any room with a vent"],
    },
    {
      name: "Decontaminate",
      types: ["Short"],
      locations: ["Main Hall"],
    },
    {
      name: "Develop Photos",
      types: ["Long"],
      locations: ["Main Hall"],
    },
    {
      name: "Divert Power",
      types: ["Short"],
      locations: [
        "Electrical",
        "Armory",
        "Cockpit",
        "Engine Room",
        "Gap Room",
        "Main Hall",
        "Meeting Room",
        "Showers",
      ],
    },
    {
      name: "Dress Mannequin",
      types: ["Short"],
      locations: ["Vault"],
    },
    {
      name: "Empty Garbage",
      types: ["Long"],
      locations: ["Kitchen", "Main Hall", "Medical", "Meeting Room"],
    },
    {
      name: "Enter Id Code",
      types: ["Common"],
      locations: ["Meeting Room"],
    },
    {
      name: "Fix Shower",
      types: ["Short"],
      locations: ["Showers"],
    },
    {
      name: "Fix Wiring",
      types: ["Common"],
      locations: [
        "Viewing Deck",
        "Engine Room",
        "Main Hall",
        "Showers",
        "Lounge",
        "Cargo Bay",
        "Meeting Room",
      ],
    },
    {
      name: "Fuel Engines",
      types: ["Long"],
      locations: ["Cargo Bay", "Engine Room"],
    },
    {
      name: "Make Burger",
      types: ["Short"],
      locations: ["Kitchen"],
    },
    {
      name: "Pick Up Towels",
      types: ["Short"],
      locations: ["Showers"],
    },
    {
      name: "Polish Ruby",
      types: ["Short"],
      locations: ["Vault"],
    },
    {
      name: "Put Away Pistols",
      types: ["Short"],
      locations: ["Armory"],
    },
    {
      name: "Put Away Rifles",
      types: ["Short"],
      locations: ["Armory"],
    },
    {
      name: "Reset Breakers",
      types: ["Long"],
      locations: ["Electrical"],
    },
    {
      name: "Rewind Tapes",
      types: ["Long"],
      locations: ["Security"],
    },
    {
      name: "Sort Records",
      types: ["Short"],
      locations: ["Records"],
    },
    {
      name: "Stabilize Steering",
      types: ["Short"],
      locations: ["Cockpit"],
    },
    {
      name: "Start Fans",
      types: ["Long"],
      locations: ["Ventilation"],
    },
    {
      name: "Unlock Safe",
      types: ["Long"],
      locations: ["Cargo Bay"],
    },
    {
      name: "Upload Data",
      types: ["Long"],
      locations: [
        "Armory",
        "Brig",
        "Cargo Bay",
        "Cockpit",
        "Communications",
        "Gap Room",
        "Medical",
        "Records",
        "Vault",
        "Viewing Deck",
        "Viewing Deck",
        "Security",
      ],
    },
  ],
  "mira-hq": [
    {
      name: "Assemble Artifact",
      types: ["Short"],
      locations: ["Laboratory"],
    },
    {
      name: "Buy Beverage",
      types: ["Short"],
      locations: ["Cafeteria"],
    },
    {
      name: "Chart Course",
      types: ["Short"],
      locations: ["Admin"],
    },
    {
      name: "Clean O2 Filter",
      types: ["Short"],
      locations: ["Greenhouse"],
    },
    {
      name: "Clean Vent",
      types: ["Short"],
      locations: ["Any room with a vent"],
    },
    {
      name: "Clear Asteroids",
      types: ["Long"],
      locations: ["Balcony"],
    },
    {
      name: "Divert Power",
      types: ["Long", "Short if Laboratory"],
      locations: [
        "Reactor",
        "Admin",
        "Cafeteria",
        "Communications",
        "Greenhouse",
        "Laboratory",
        "Launchpad",
        "MedBay",
        "Office",
      ],
    },
    {
      name: "Empty Garbage",
      types: ["Short"],
      locations: ["Cafeteria"],
    },
    {
      name: "Enter Id Code",
      types: ["Common"],
      locations: ["Admin"],
    },
    {
      name: "Fix Wiring",
      types: ["Common"],
      locations: [
        "Storage",
        "Hallway",
        "Locker Room",
        "Greenhouse",
        "Laboratory",
      ],
    },
    {
      name: "Fuel Engines",
      types: ["Short"],
      locations: ["Launchpad"],
    },
    {
      name: "Measure Weather",
      types: ["Short"],
      locations: ["Balcony"],
    },
    {
      name: "Prime Shields",
      types: ["Short"],
      locations: ["Admin"],
    },
    {
      name: "Process Data",
      types: ["Short"],
      locations: ["Office"],
    },
    {
      name: "Run Diagnostics",
      types: ["Short"],
      locations: ["Launchpad"],
    },
    {
      name: "Sort Samples",
      types: ["Short"],
      locations: ["Laboratory"],
    },
    {
      name: "Start Reactor",
      types: ["Long"],
      locations: ["Reactor"],
    },
    {
      name: "Submit Scan",
      types: ["Long", "Visual"],
      locations: ["MedBay"],
    },
    {
      name: "Unlock Manifolds",
      types: ["Short"],
      locations: ["Reactor"],
    },
    {
      name: "Water Plants",
      types: ["Long"],
      locations: ["Storage", "Greenhouse"],
    },
  ],
  polus: [
    {
      name: "Align Telescope",
      types: ["Short"],
      locations: ["Laboratory"],
    },
    {
      name: "Chart Course",
      types: ["Short"],
      locations: ["Dropship"],
    },
    {
      name: "Clear Asteroids",
      types: ["Short", "Visual"],
      locations: ["Weapons"],
    },
    {
      name: "Empty Garbage",
      types: ["Short"],
      locations: ["O2"],
    },
    {
      name: "Fill Canisters",
      types: ["Short"],
      locations: ["O2"],
    },
    {
      name: "Fix Weather Node",
      types: ["Long"],
      locations: ["Outside", "Laboratory"],
    },
    {
      name: "Fix Weather Node",
      types: ["Short"],
      locations: ["Outside", "Laboratory"],
    },
    {
      name: "Fix Wiring",
      types: ["Common"],
      locations: [
        "Electrical",
        "O2",
        "Office",
        "Decontamination",
        "Laboratory",
        "Laboratory",
      ],
    },
    {
      name: "Fuel Engines",
      types: ["Long"],
      locations: [
        "Storage",
        "Outside",
        "Dropship",
        "Storage",
        "Outside",
        "Dropship",
      ],
    },
    {
      name: "Insert Keys",
      types: ["Common"],
      locations: ["Dropship"],
    },
    {
      name: "Inspect Sample",
      types: ["Long"],
      locations: ["MedBay"],
    },
    {
      name: "Monitor Tree",
      types: ["Short"],
      locations: ["O2"],
    },
    {
      name: "Open Waterways",
      types: ["Long"],
      locations: ["Boiler Room", "Boiler Room", "Outside", "Office"],
    },
    {
      name: "Reboot Wifi",
      types: ["Long"],
      locations: ["Communications"],
    },
    {
      name: "Record Temperature",
      types: ["Short"],
      locations: ["Laboratory", "Outside"],
    },
    {
      name: "Repair Drill",
      types: ["Short"],
      locations: ["Laboratory"],
    },
    {
      name: "Replace Water Jug",
      types: ["Long"],
      locations: ["Boiler Room", "Office"],
    },
    {
      name: "Scan Boarding Pass",
      types: ["Common"],
      locations: ["Office"],
    },
    {
      name: "Start Reactor",
      types: ["Long"],
      locations: ["Specimen Room"],
    },
    {
      name: "Store Artifacts",
      types: ["Short"],
      locations: ["Specimen Room"],
    },
    {
      name: "Submit Scan",
      types: ["Short", "Visual"],
      locations: ["MedBay"],
    },
    {
      name: "Swipe Card",
      types: ["Common"],
      locations: ["Office"],
    },
    {
      name: "Unlock Manifolds",
      types: ["Short"],
      locations: ["Specimen Room"],
    },
    {
      name: "Upload Data",
      types: ["Long"],
      locations: [
        "Electrical",
        "O2",
        "Office",
        "Specimen Room",
        "Weapons",
        "Communications",
      ],
    },
  ],
  "the-fungle": [
    {
      name: "Assemble Artifact",
      types: ["Short"],
      locations: ["Laboratory"],
    },
    {
      name: "Build Sandcastle",
      types: ["Short"],
      locations: ["Splash Zone"],
    },
    {
      name: "Collect Vegetables",
      types: ["Long"],
      locations: ["Greenhouse", "Kitchen"],
    },
    {
      name: "Cook Fish",
      types: ["Long"],
      locations: ["Dock", "Kitchen"],
    },
    {
      name: "Collect Samples",
      types: ["Common"],
      locations: ["Jungle", "Laboratory"],
    },
    {
      name: "Collect Shells",
      types: ["Short"],
      locations: ["Beach", "Splash zone"],
    },
    {
      name: "Crank Generator",
      types: ["Short"],
      locations: ["Communications", "Kitchen"],
    },
    {
      name: "Empty Garbage",
      types: ["Short"],
      locations: ["Cafetaria", "Splash Zone"],
    },
    {
      name: "Enter Id Code",
      types: ["Common"],
      locations: ["Admin", "Meeting Room", "Lookout"],
    },
    {
      name: "Extract Fuel",
      types: ["Long"],
      locations: ["Upper Engine", "Storage"],
    },
    {
      name: "Find Signal",
      types: ["Short"],
      locations: ["Communications"],
    },
    {
      name: "Fix Antenna",
      types: ["Short"],
      locations: ["Communications"],
    },
    {
      name: "Fix Wiring",
      types: ["Short"],
      locations: ["Communications", "Dropship"],
    },
    {
      name: "Help Critter",
      types: ["Long"],
      locations: ["Jungle", "Laboratory"],
    },
    {
      name: "Hoist Supplies",
      types: ["Long"],
      locations: ["Jungle", "The Cliffs"],
    },
    {
      name: "Lift Weights",
      types: ["Short"],
      locations: ["Splash Zone"],
    },
    {
      name: "Mine Ores",
      types: ["Long"],
      locations: ["Mining Pit"],
    },
    {
      name: "Monitor Mushroom",
      types: ["Short"],
      locations: ["Jungle"],
    },
    {
      name: "Play Video Game",
      types: ["Short"],
      locations: ["The Dorm"],
    },
    {
      name: "Polish Gem",
      types: ["Long"],
      locations: ["Mining Pit"],
    },
    {
      name: "Record Temperature",
      types: ["Short"],
      locations: ["Greenhouse", "Laboratory", "Reactor"],
    },
    {
      name: "Replace Parts",
      types: ["Common"],
      locations: ["Reactor", "Upper Engine", "Communications", "Dropship"],
    },
    {
      name: "Replace Water Jug",
      types: ["Long"],
      locations: ["Storage", "Cafetaria"],
    },
    {
      name: "Roast Marshmellow",
      types: ["Common"],
      locations: ["Beach (random sand pile)", "Beach (central campfire)"],
    },
    {
      name: "Throw Frisbee",
      types: ["Short"],
      locations: ["Splash Zone"],
    },
    {
      name: "Water Plants",
      types: ["Long"],
      locations: ["Storage", "Greenhouse"],
    },
  ],
};
